/vis/open OGL
/vis/drawVolume
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton magenta
/vis/modeling/trajectories/drawByParticleID-0/set gamma white
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
/vis/scene/endOfEventAction accumulate 1
/run/beamOn 1
